version: "3.9"  # optional since v1.27.0
services:
  app:
    build: .
    container_name: app
    depends_on:
      - postgres
    networks:
      - myNet
    ports:
      - ${PORT}:${PORT}
    logging:
      driver: json-file
    volumes:
      - logs:/user/app/src/logs
      - ./src:/user/app/src
    environment:
      POSTGRES_HOST: postgres
    restart: always 
  postgres:
    build: ./src/db
    container_name: database
    networks:
      - myNet
    ports:
      - ${POSTGRES_CONTAINERPORT}:${POSTGRES_CONTAINERPORT}
    volumes:
      - pg_data:/var/lib/postgressql/data/pgdata    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgressql/data/pgdata
    restart: always  
networks:
  myNet:
volumes:
  logs:
  pg_data:


